# Generated by Django 4.2.1 on 2023-05-12 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('extra_messages', models.IntegerField(null=True)),
                ('day_limit_of_messages', models.IntegerField(null=True)),
                ('day_of_limit', models.DateField()),
                ('premium_status', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_mode', models.CharField(blank=True, choices=[('you', 'you'), ('poe', 'poe'), ('forefront', 'forefront'), ('theb', 'thed')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
