# Generated by Django 4.2.1 on 2023-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_user',
            name='day_of_limit',
            field=models.DateField(null=True),
        ),
    ]
