# Generated by Django 4.2.1 on 2023-05-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messages_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-datetime'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
